//
//  SmallPictureModel.swift
//  MusicApp
//
//  Created by Eduard Caziuc on 18.04.2022.
//

import SwiftUI

struct SmallPictureModel: Hashable, Identifiable {
  var id = UUID()
  var image: String
  var name: String
  var description: String
}

var radioStations = [
  SmallPictureModel(image: "smallradio0", name: "Up Next", description: "Apple Music"),
  SmallPictureModel(image: "smallradio1", name: "Africa Now", description: "Apple Music"),
  SmallPictureModel(image: "smallradio2", name: "John Legend", description: "Apple Music"),
  SmallPictureModel(image: "smallradio3", name: "Placeholder", description: "Apple Music"),
  SmallPictureModel(image: "smallradio4", name: "Billie Eilish", description: "Apple Music"),
  SmallPictureModel(image: "smallradio5", name: "Placeholder", description: "Apple Music"),
  SmallPictureModel(image: "smallradio6", name: "Placeholder", description: "Apple Music")
]

var musicPlaylists: [Media] = [
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p0"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p1"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p2"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p1"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p3"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p4"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p5"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p6"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p7"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p8"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p9"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p10"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p11"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p12"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p13"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p14"), composer: "Lil Peep", isCompilation: nil))
]

var musicPlaylists2: [Media] = [
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p0"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p1"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p2"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p1"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p3"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p4"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p5"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p6"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p7"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p8"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p9"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p10"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p11"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p12"), composer: "Lil Peep", isCompilation: nil)),
  
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p13"), composer: "Lil Peep", isCompilation: nil)),
  Media(mediaResponse: MediaResponse(id: UUID().uuidString, artistId: 0, collectionId: 0, trackId: 0, wrapperType: "track", kind: "Album", name: "Lil Peep", artistName: "Lil Peep", collectionName: "Essentials", trackName: "Star Shopping", collectionCensoredName: "Essentials", artistViewUrl: nil, collectionViewUrl: nil, trackViewUrl: nil, previewUrl: nil, artworkUrl100: nil, collectionPrice: nil, collectionHdPrice: 0, trackPrice: 0, collectionExplicitness: nil, trackExplicitness: "explicit", discCount: 1, discNumber: 1, trackCount: 10, trackNumber: 1, trackTimeMillis: 3000, country: "USA", currency: "USD", primaryGenreName: "Hip-Hop/Rap", description: "Description", longDescription: nil, releaseDate: Date().ISO8601Format(), contentAdvisoryRating: nil, trackRentalPrice: 10, artwork: UIImage(named: "p14"), composer: "Lil Peep", isCompilation: nil))
]
