//
//  SmallPictureModel.swift
//  MusicApp
//
//  Created by Eduard Caziuc on 18.04.2022.
//

import SwiftUI

struct SmallPictureModel: Hashable, Identifiable {
    var id = UUID()
    var image: String
    var name: String
    var description: String
}

var radioStations = [
    SmallPictureModel(image: "smallradio0", name: "Up Next", description: "Apple Music"),
    SmallPictureModel(image: "smallradio1", name: "Africa Now", description: "Apple Music"),
    SmallPictureModel(image: "smallradio2", name: "John Legend", description: "Apple Music"),
    SmallPictureModel(image: "smallradio3", name: "Placeholder", description: "Apple Music"),
    SmallPictureModel(image: "smallradio4", name: "Billie Eilish", description: "Apple Music"),
    SmallPictureModel(image: "smallradio5", name: "Placeholder", description: "Apple Music"),
    SmallPictureModel(image: "smallradio6", name: "Placeholder", description: "Apple Music")
]

var musicPlaylists: [Media] = [
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio7"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio8"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio9"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio10"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio11"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio12"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio13"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio14"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio15"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio16"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio17"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio18"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio19"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio20"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio21"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date())
]

var musicPlaylists2: [Media] = [
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Lil Peep", collectionName: "Essentials", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio0"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Billie Eilish", collectionName: "Album", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio1"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "070 Shake", collectionName: "Honey", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio2"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "6ix9ine", collectionName: "Graduation Day", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio3"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "XXXTENTACION", collectionName: "?", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio4"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Bob Dylan", collectionName: "The Freewheelin' Bob Dylan", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio5"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date()),
//    Media(id: UUID().uuidString, wrapperType: .collection, kind: .album, artistName: "Post Malone", collectionName: "Stoney", trackName: "Apple Music", collectionPrice: 12, trackPrice: 12, discCount: 1, discNumber: 1, trackCount: 5, trackNumber: 1, trackTimeMillis: 400, country: "USA", primaryGenreName: "Rap", artwork: Image("smallradio6"), artworkUIImage: UIImage(named: "smallradio0"), releaseDate: Date(), dateAdded: Date())
    
]
